# Generated by Django 4.1 on 2022-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(default='ProfileImages/default.jpg', upload_to='ProfileImages'),
        ),
    ]
