# Generated by Django 4.1 on 2022-08-25 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusermodel_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='ProfileImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'gif', 'bmp'])]),
        ),
    ]
