# Generated by Django 4.1 on 2022-08-31 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='expire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
