# Generated by Django 4.1 on 2022-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailcode_code_alter_emailcode_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailcode',
            name='email',
            field=models.EmailField(default='pixel@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
