# Generated by Django 4.1.1 on 2022-10-16 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customusermodel_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(default='ProfileImages/default.jpg', upload_to='ProfileImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'gif', 'bmp'])]),
        ),
    ]
