# Generated by Django 4.1.1 on 2022-10-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customusermodel_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='users_user_model',
        ),
        migrations.AlterModelTable(
            name='emailcode',
            table='users_email_code',
        ),
    ]
