# Generated by Django 4.1.3 on 2022-11-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customusermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusermodel',
            table='users',
        ),
        migrations.AlterModelTable(
            name='emailcode',
            table='email_codes',
        ),
    ]
