# Generated by Django 4.1.3 on 2022-12-03 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customusermodel_table_alter_emailcode_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(default='ProfileImages/default.jpg', upload_to='ProfileImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
    ]
