# Generated by Django 4.1.1 on 2022-10-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
