# Generated by Django 4.1.1 on 2022-10-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_post_dislikes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
