# Generated by Django 4.1.3 on 2022-11-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
