# Generated by Django 4.1 on 2022-08-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
    ]
