# Generated by Django 4.1.1 on 2022-10-16 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_app', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='forum_comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='forum_post',
        ),
    ]
